### PR TITLE
Adapt workflows

### PR DESCRIPTION
**Pull request by constantinpape**
Start to work on some of the issues listed in #49 and start to use hdf5 tables for intermediate results.

### CODE REVIEW

**Comment by constantinpape** [comment]
Overall h5 table functionality should be working now, but still some stuff to do:
1. Move infected cell detection and `preprocess_per_cell_statistic` to separate job(s), [see here](https://github.com/hci-unihd/batchlib/blob/workflows/batchlib/analysis/cell_level_analysis.py#L428-L431)
2. Change logic of arguments for the outlier detection, [see here](https://github.com/hci-unihd/batchlib/blob/workflows/batchlib/workflows/cell_analysis.py#L218-L221)
3. Clean up the scripts in `antibodies` 
4. Fix tests and make sure all results are correct ...

Also, we should keep in mind making it easier to re-run the pipeline smoothly in the same folder with different hyperparameters and for different input keys (e.g. `serum_iga` vs. `serum_igg`).
(Should be done in a separate PR though)

cc @imagirom

**Comment by constantinpape** [comment]
I don't think the way we pass the arguments for the outlier predicate make sense right now: https://github.com/hci-unihd/batchlib/blob/workflows/batchlib/workflows/cell_analysis.py#L224-L231
I would rather not pass any additional arguments and check in `misc/tagged_outliers` if we have a `<PLATE NAME>_tagger_state.csv`. Note that we get the `misc_folder` location as an argument.
@wolny would this make sense?

**Comment by wolny** [comment]
@constantinpape do you refer to the construction of the `OutlierPredictate` as in here: https://github.com/hci-unihd/batchlib/blob/master/batchlib/outliers/outlier.py#L50? By default we do take `misc/tagged_outliers` if nothing was given: https://github.com/hci-unihd/batchlib/blob/master/batchlib/outliers/outlier.py#L16. The `plate_name` needs to be specified somewhere though

**Comment by constantinpape** [comment]
>  The `plate_name` needs to be specified somewhere though

But this always corresponds to the folder name.
So I don't understand why you give the arguments to the parser when it doesn't make sense to use anything but the default values anyways.

**Comment by wolny** [comment]
ah you mean removing those: https://github.com/hci-unihd/batchlib/blob/workflows/batchlib/workflows/cell_analysis.py#L257-L260? Sure I agree, it's obsolete now

**Comment by constantinpape** [comment]
This is moving along pretty good. From my side most of the major changes are done.

Before merging, the following things should still be done:
- check that results look good for a big plate to check that we don't have any obvious bugs. @tischi, could you do this at some point tomorrow? I am computing this right now: `/g/kreshuk/data/covid/sandbox/h5-tables2/titration_plate_20200403_154849`, should be there in the morning.
- make sure that the plot function still work properly, I changed quite a few things in there ... Could you have a look at this at some point, @imagirom?
- Fix #67. I will look into this.

In addition, @imagirom is working on the infected cell detection and the background subtraction now.
We can merge this PR independently of this, but can also wait for it, I don't mind either way.

Also there's a few smaller things I still want to do, but we don't need to wait for this either.
Just putting it here so I can keep track of it:
- Try hdf5 tables with varlen strings (need to check if this works with java)
- Use the same plot function for image level and well level plots
- Clean up TODOs and FIXMEs. There are still quite a few of these scattered throughout the code that are either outdated or easy to fix.

**Comment by imagirom** [comment]
I have added some commits towards proper background subtraction and better infected cell detection (In particular fixed a bug where nuclei were considered background in 3b3c39f).

Also, the IgG serum channel is now used by default for the boundary predictions (as they were trained on that channel), see f7952c1.

I will check some of the plots tomorrow. 

All the preliminary work for #53, #54, #55 should be done, so I should be able to address all of those tomorrow.

**Pull request merged**
